version: '3'

services:
    category-app:
      build: .
      volumes:
        - ./:/var/www
      depends_on:
        - category-app-mysql
      
    category-app-mysql:
      image: mysql:latest
      restart: always
      ports:
        - "3306"
      volumes:
        - "./.docker/db:/var/lib/mysql"
      environment:
        MYSQL_DATABASE: uniforca
        MYSQL_ROOT_PASSWORD: root

    category-app-phpmyadmin:
      image: phpmyadmin:latest
      depends_on:
        - category-app-mysql
      restart: always
      ports:
        - "81:80"
      environment:
        PMA_HOST: category-app-mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      
    category_app-nginx:
      build: ./.docker/nginx
      restart: always
      ports: 
        - "7777:80"
      volumes: 
        - ./:/var/www
      depends_on:
        - category-app
      

